[tool.black]
line-length = 100
target-version = ["py311"]
include = "backend/.*\.py"

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app"]
src_paths = ["backend/app", "backend/tests"]

