name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black==24.8.0 isort==5.13.2 flake8==7.0.0 flake8-bugbear==24.4.26 flake8-comprehensions==3.14.0

      - name: Lint - black
        run: black --check --line-length 100 app tests

      - name: Lint - isort
        run: isort --check-only --profile black --line-length 100 app tests

      - name: Lint - flake8
        run: flake8 app tests

      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings

